server:
  port: 8082
spring:
  application:
    name: HOTEL-SERVICE
  config:
    import: optional:configserver:http://localhost8085
  datasource:
    url: jdbc:postgresql://localhost:5432/dataHotel
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



